apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodStatus
  labels:
    app: prodStatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prodStatus
  template:
    metadata:
      labels:
        app: prodStatus
    spec:
      containers:
        - name: prodStatus
          image: username/prodStatus:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5