---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-order
  labels:
    app: work-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work-order
  template:
    metadata:
      labels:
        app: work-order
    spec:
      containers:
        - name: work-order
          image: username/work-order:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes
  labels:
    app: mes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mes
  template:
    metadata:
      labels:
        app: mes
    spec:
      containers:
        - name: mes
          image: username/mes:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    app: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: username/master:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 생산현황관리
  labels:
    app: 생산현황관리
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 생산현황관리
  template:
    metadata:
      labels:
        app: 생산현황관리
    spec:
      containers:
        - name: 생산현황관리
          image: username/생산현황관리:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: work-order
  labels:
    app: work-order
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: work-order


---


apiVersion: v1
kind: Service
metadata:
  name: mes
  labels:
    app: mes
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mes


---


apiVersion: v1
kind: Service
metadata:
  name: master
  labels:
    app: master
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: master


---


apiVersion: v1
kind: Service
metadata:
  name: 생산현황관리
  labels:
    app: 생산현황관리
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 생산현황관리

